
# project configuration
project_id = "pikxpmhpcsrstmikkpvg"

[functions.whatsapp]
verify_jwt = true

[functions.mercadopago]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

