
project_id = "pikxpmhpcsrstmikkpvg"

[functions.mercadopago]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.check-mercadopago-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-checkout]
verify_jwt = true

[functions.process-notifications]
verify_jwt = true

[functions.delete-client]
verify_jwt = true
